var str = "somnath sumbe";
console.log(str);
console.log(typeof (str));
var str1 = "sunita";
console.log(str1);
console.log(typeof (str1));
var result = str + " hi how are you " + str1;
console.log(result);
console.log(typeof (result));
var isactive = true;
console.log(isactive);
console.log(typeof (isactive));
var isupdate = false;
console.log(isupdate);
console.log(typeof (isupdate));
